// Mr Pizzeria - Comprehensive Menu Data & Ratings for Swiggy/Zomato Mobile Experience

const MENU_CATEGORIES = [
  { id: "all", name: "All", icon: "✨" },
  { id: "pizzas", name: "Pizzas", icon: "🍕", img: "🍕" },
  { id: "burgers", name: "Burgers", icon: "🍔", img: "🍔" },
  { id: "sandwiches", name: "Sandwiches", icon: "🥪", img: "🥪" },
  { id: "puffs", name: "Puffs & Bites", icon: "🥐", img: "🥐" },
  { id: "fries", name: "Fries", icon: "🍟", img: "🍟" },
  { id: "shakes", name: "Shakes", icon: "🥤", img: "🥤" },
  { id: "mojitos", name: "Mojitos", icon: "🍹", img: "🍹" },
  { id: "desserts", name: "Desserts", icon: "🍰", img: "🍰" }
];

const PROMO_BANNERS = [
  {
    id: 1,
    title: "⚡ Bikramganj's Fastest Delivery",
    subtitle: "Piping hot pizzas delivered in 25 mins!",
    tag: "SPEEDY 25M",
    bgGradient: "linear-gradient(135deg, #ff416c, #ff4b2b)"
  },
  {
    id: 2,
    title: "🧀 Triple Cheese Burst Special",
    subtitle: "Loaded with 3 premium melted cheeses",
    tag: "CHEF PICK",
    bgGradient: "linear-gradient(135deg, #f7971e, #ffd200)"
  },
  {
    id: 3,
    title: "🎉 Shivhari Food Hub Network",
    subtitle: "Order Cakes, Biryani, Dosa & Sweets too",
    tag: "7 SERVICES",
    bgGradient: "linear-gradient(135deg, #11998e, #38ef7d)"
  }
];

const SHIVHARI_SERVICES = [
  { code: "1", title: "Cakes & Bakery", icon: "🎂", subtitle: "केक और बेकरी", desc: "Fresh customized celebration cakes" },
  { code: "2", title: "Mr Pizzeria", icon: "🍕", subtitle: "मिस्टर पिज्जा", desc: "Cheesy pizzas, burgers & shakes (Active Menu)", active: true },
  { code: "3", title: "Restaurant Meals", icon: "🍽️", subtitle: "रेस्टोरेंट भोजन", desc: "North Indian, Chinese & Combos" },
  { code: "4", title: "Umesh Dosa & Chat", icon: "🥞", subtitle: "उमेश डोसा & चाट", desc: "Crispy dosas, chaat & snacks" },
  { code: "5", title: "Sweets & Mithai", icon: "🍬", subtitle: "स्वीट्स & मिठाई", desc: "Traditional fresh Indian sweets" },
  { code: "6", title: "Birthday Items", icon: "🎉", subtitle: "बर्थडे पार्टी सामान", desc: "Balloons, party poppers & decor" },
  { code: "8", title: "Biryani House", icon: "🍲", subtitle: "बिरयानी हाउस", desc: "Aromatic dum biryani specials" }
];

const MENU_ITEMS = [
  // --- PIZZAS ---
  {
    id: "piz-umesh-spl",
    categoryId: "pizzas",
    name: "Umesh Special Pizza",
    icon: "🍕",
    rating: "4.9",
    votes: "142",
    desc: "Mozzarella, sweet corn, mushrooms, fresh paneer, capsicum, black olives & red paprika with secret spices.",
    tags: ["Bestseller", "Chef Special"],
    isVeg: true,
    hasSizes: true,
    prices: { small: 180, medium: 280, large: 430 },
    defaultSize: "medium"
  },
  {
    id: "piz-triple-cheese",
    categoryId: "pizzas",
    name: "Triple Layer Cheese Pizza",
    icon: "🧀",
    rating: "4.8",
    votes: "128",
    desc: "Loaded with crunchy onion, crisp capsicum, spicy jalapenos and 3 mouth-watering cheese flavors.",
    tags: ["Bestseller", "Cheesy"],
    isVeg: true,
    hasSizes: true,
    prices: { small: 220, medium: 300, large: 400 },
    defaultSize: "medium"
  },
  {
    id: "piz-exotica",
    categoryId: "pizzas",
    name: "Exotica Pizza",
    icon: "🥦",
    rating: "4.7",
    votes: "95",
    desc: "Broccoli florets, juicy cherry tomatoes, mushrooms, signature pizza sprinkle, mozzarella & red paprika.",
    tags: ["Gourmet"],
    isVeg: true,
    hasSizes: true,
    prices: { small: 200, medium: 280, large: 380 },
    defaultSize: "medium"
  },
  {
    id: "piz-paneer-smoky",
    categoryId: "pizzas",
    name: "Paneer Smoky Pizza",
    icon: "🔥",
    rating: "4.8",
    votes: "116",
    desc: "Charred BBQ paneer cubes, red onions, capsicum, red paprika and black olives on smoky sauce.",
    tags: ["Spicy", "Popular"],
    isVeg: true,
    hasSizes: true,
    prices: { small: 180, medium: 280, large: 380 },
    defaultSize: "medium"
  },
  {
    id: "piz-jain",
    categoryId: "pizzas",
    name: "Jain Pizza",
    icon: "🌿",
    rating: "4.7",
    votes: "78",
    desc: "Specially prepared 100% Jain pizza with sweet corn, mushroom, black olives & red paprika. No onion, no garlic.",
    tags: ["Pure Jain"],
    isVeg: true,
    isJain: true,
    hasSizes: true,
    prices: { small: 150, medium: 250, large: 350 },
    defaultSize: "medium"
  },
  {
    id: "piz-margherita",
    categoryId: "pizzas",
    name: "Classic Margherita Pizza",
    icon: "🧀",
    rating: "4.6",
    votes: "110",
    desc: "Authentic single-origin Mozzarella cheese with aromatic Italian herbs and fresh tomato concasse.",
    tags: ["Classic"],
    isVeg: true,
    hasSizes: true,
    prices: { small: 120, medium: 200, large: 300 },
    defaultSize: "small"
  },
  {
    id: "piz-mix-veg",
    categoryId: "pizzas",
    name: "Mix Vegetable Pizza",
    icon: "🥗",
    rating: "4.5",
    votes: "84",
    desc: "Fresh diced onions, red & yellow bell peppers, crisp capsicum and vibrant red paprika.",
    tags: ["Fresh Veg"],
    isVeg: true,
    hasSizes: true,
    prices: { small: 150, medium: 250, large: 350 },
    defaultSize: "medium"
  },
  {
    id: "piz-paneer-tikka",
    categoryId: "pizzas",
    name: "Paneer Tikka Pizza",
    icon: "🧀",
    rating: "4.9",
    votes: "155",
    desc: "Tandoori spiced paneer cubes, crunchy green capsicum, black olives and fiery red paprika.",
    tags: ["Bestseller"],
    isVeg: true,
    hasSizes: true,
    prices: { small: 160, medium: 260, large: 380 },
    defaultSize: "medium"
  },
  {
    id: "piz-paneer-tandoori",
    categoryId: "pizzas",
    name: "Paneer Tandoori Pizza",
    icon: "🍢",
    rating: "4.8",
    votes: "102",
    desc: "Rich tandoori gravy sauce topped with marinated paneer, capsicum, olives & paprika.",
    tags: ["Tandoori"],
    isVeg: true,
    hasSizes: true,
    prices: { small: 160, medium: 260, large: 380 },
    defaultSize: "medium"
  },
  {
    id: "piz-corn-cheese",
    categoryId: "pizzas",
    name: "Corn Cheese Pizza",
    icon: "🌽",
    rating: "4.6",
    votes: "89",
    desc: "Golden sweet corn kernels smothered in molten mozzarella cheese & capsicum.",
    tags: ["Kids Fav"],
    isVeg: true,
    hasSizes: true,
    prices: { small: 150, medium: 240, large: 350 },
    defaultSize: "small"
  },
  {
    id: "piz-double-cheese",
    categoryId: "pizzas",
    name: "Double Cheese Pizza",
    icon: "🧀",
    rating: "4.8",
    votes: "98",
    desc: "Double dose of gooey mozzarella and processed cheese with your favorite toppings.",
    tags: ["Cheesy"],
    isVeg: true,
    hasSizes: true,
    prices: { small: 180, medium: 260, large: 360 },
    defaultSize: "medium"
  },
  {
    id: "piz-spl-mushroom",
    categoryId: "pizzas",
    name: "Special Mushroom Pizza",
    icon: "🍄",
    rating: "4.6",
    votes: "64",
    desc: "Fresh button mushrooms, liquid melted cheese, mozzarella blend and sliced black olives.",
    tags: ["Mushroom"],
    isVeg: true,
    hasSizes: true,
    prices: { small: 180, medium: 260, large: 360 },
    defaultSize: "medium"
  },
  {
    id: "piz-cheese-burst",
    categoryId: "pizzas",
    name: "Cheese Burst Pizza",
    icon: "💥",
    rating: "4.9",
    votes: "160",
    desc: "Decadent crust bursting with oozing hot liquid mozzarella, processed cheese & premium veggies.",
    tags: ["Bestseller", "Must Try"],
    isVeg: true,
    hasSizes: true,
    prices: { small: 200, medium: 300, large: 450 },
    defaultSize: "medium"
  },
  {
    id: "piz-extra-cheese",
    categoryId: "pizzas",
    name: "Extra Cheese Add-on",
    icon: "🧀",
    rating: "4.9",
    votes: "210",
    desc: "Add an extra generous layer of molten mozzarella cheese to any pizza.",
    tags: ["Add-on"],
    isVeg: true,
    hasSizes: false,
    price: 50
  },

  // --- BURGERS ---
  {
    id: "bur-classic-veg",
    categoryId: "burgers",
    name: "Classic Veg Burger",
    icon: "🍔",
    rating: "4.5",
    votes: "72",
    desc: "Crisp seasoned veggie patty with sliced tomato, crisp onion & house mayo sauce.",
    tags: ["Classic"],
    isVeg: true,
    hasSizes: false,
    price: 90
  },
  {
    id: "bur-classic-veg-cheese",
    categoryId: "burgers",
    name: "Classic Veg Cheese Burger",
    icon: "🧀",
    rating: "4.7",
    votes: "88",
    desc: "Crispy vegetable patty topped with melted cheese slice and creamy burger mayo.",
    tags: ["Cheesy"],
    isVeg: true,
    hasSizes: false,
    price: 110
  },
  {
    id: "bur-aloo-tikki",
    categoryId: "burgers",
    name: "Aloo Tikki Burger",
    icon: "🥔",
    rating: "4.4",
    votes: "65",
    desc: "Golden crunchy spiced aloo patty with crunchy onions and tangy desi mint dressing.",
    tags: ["Crisp"],
    isVeg: true,
    hasSizes: false,
    price: 80
  },
  {
    id: "bur-aloo-tikki-cheese",
    categoryId: "burgers",
    name: "Aloo Tikki Cheese Burger",
    icon: "🧀",
    rating: "4.6",
    votes: "76",
    desc: "Crunchy aloo tikki topped with molten cheddar slice and spicy burger spread.",
    tags: ["Popular"],
    isVeg: true,
    hasSizes: false,
    price: 100
  },
  {
    id: "bur-royal-paneer",
    categoryId: "burgers",
    name: "Royal Paneer Burger",
    icon: "🧀",
    rating: "4.8",
    votes: "94",
    desc: "Thick grilled paneer patty seasoned with herbs, crunchy lettuce and gourmet mayo.",
    tags: ["High Protein"],
    isVeg: true,
    hasSizes: false,
    price: 90
  },
  {
    id: "bur-royal-paneer-cheese",
    categoryId: "burgers",
    name: "Royal Paneer Cheese Burger",
    icon: "👑",
    rating: "4.9",
    votes: "135",
    desc: "Spiced paneer slab layered with double cheese slices, crispy veggies and royal sauce.",
    tags: ["Bestseller", "Royal"],
    isVeg: true,
    hasSizes: false,
    price: 100
  },
  {
    id: "bur-pizzeria-spl",
    categoryId: "burgers",
    name: "Pizzeria Spl. Monster Burger",
    icon: "⭐",
    rating: "4.9",
    votes: "112",
    desc: "Our signature giant monster burger loaded with double patties, double cheese layers & chef's secret spicy relish.",
    tags: ["Chef Special", "Monster"],
    isVeg: true,
    hasSizes: false,
    price: 150
  },

  // --- SANDWICHES ---
  {
    id: "snd-aloo-cheese",
    categoryId: "sandwiches",
    name: "Aloo Cheese Slice Sandwich",
    icon: "🥔",
    rating: "4.5",
    votes: "60",
    desc: "Homestyle spiced potato mash with melted cheese slice grilled in butter.",
    tags: ["Quick Bite"],
    isVeg: true,
    hasSizes: false,
    price: 50
  },
  {
    id: "snd-bread-butter-jam",
    categoryId: "sandwiches",
    name: "Bread Butter Jam Sandwich",
    icon: "🍓",
    rating: "4.3",
    votes: "42",
    desc: "Sweet and buttery layered classic fruit jam sandwich.",
    tags: ["Sweet"],
    isVeg: true,
    hasSizes: false,
    price: 50
  },
  {
    id: "snd-veg-club-3layer",
    categoryId: "sandwiches",
    name: "Veg Club Sandwich (3 Layer)",
    icon: "🥪",
    rating: "4.9",
    votes: "148",
    desc: "Triple layer jumbo sandwich stacked with fresh veggies, mashed potato masala, cheese & green chutney.",
    tags: ["Bestseller", "Jumbo"],
    isVeg: true,
    hasSizes: false,
    price: 160
  },
  {
    id: "snd-veg-coleslaw",
    categoryId: "sandwiches",
    name: "Veg Coleslaw Sandwich",
    icon: "🥗",
    rating: "4.6",
    votes: "55",
    desc: "Creamy shredded cabbage, carrots, bell peppers in smooth herb mayonnaise.",
    tags: ["Creamy"],
    isVeg: true,
    hasSizes: false,
    price: 100
  },
  {
    id: "snd-jain",
    categoryId: "sandwiches",
    name: "Jain Sandwich",
    icon: "🌿",
    rating: "4.7",
    votes: "62",
    desc: "Specially crafted Jain sandwich with cheese, tomatoes, capsicum and pure Jain mint chutney.",
    tags: ["Pure Jain"],
    isVeg: true,
    isJain: true,
    hasSizes: false,
    price: 120
  },
  {
    id: "snd-ghughra",
    categoryId: "sandwiches",
    name: "Ghughra Sandwich",
    icon: "🌶️",
    desc: "Spicy Surat style ghughra masala stuffing with capsicum, onion and double cheese.",
    rating: "4.8",
    votes: "86",
    tags: ["Spicy"],
    isVeg: true,
    hasSizes: false,
    price: 160
  },
  {
    id: "snd-achari",
    categoryId: "sandwiches",
    name: "Achari Sandwich",
    icon: "🥒",
    rating: "4.6",
    votes: "70",
    desc: "Tangy pickle-spiced vegetable mix with melted cheese in grilled bread.",
    tags: ["Tangy"],
    isVeg: true,
    hasSizes: false,
    price: 120
  },
  {
    id: "snd-grilled-jangali",
    categoryId: "sandwiches",
    name: "Grilled Veg Jangali Sandwich",
    icon: "🥪",
    rating: "4.7",
    votes: "79",
    desc: "Rustic spiced hearty vegetable filling grilled crisp with green herbs and cheese.",
    tags: ["Grilled"],
    isVeg: true,
    hasSizes: false,
    price: 100
  },
  {
    id: "snd-grilled-paneer-tandoori",
    categoryId: "sandwiches",
    name: "Grilled Paneer Tandoori Sandwich",
    icon: "🔥",
    rating: "4.9",
    votes: "115",
    desc: "Smoky tandoori marinated paneer slices grilled with cheese and mint sauce.",
    tags: ["Bestseller", "Tandoori"],
    isVeg: true,
    hasSizes: false,
    price: 120
  },
  {
    id: "snd-grilled-paneer-makhani",
    categoryId: "sandwiches",
    name: "Grilled Paneer Makhani Sandwich",
    icon: "🥘",
    rating: "4.8",
    votes: "92",
    desc: "Rich buttery makhani sauce glazed cottage cheese grilled between crisp bread slices.",
    tags: ["Rich"],
    isVeg: true,
    hasSizes: false,
    price: 120
  },
  {
    id: "snd-veg-garden-spl",
    categoryId: "sandwiches",
    name: "Veg Garden Spl. Sandwich",
    icon: "🥕",
    rating: "4.8",
    votes: "97",
    desc: "Loaded with garden fresh vegetables, sweet corn, olives, extra cheese & signature dressing.",
    tags: ["Special"],
    isVeg: true,
    hasSizes: false,
    price: 150
  },

  // --- PUFFS & BITES ---
  {
    id: "puff-paneer",
    categoryId: "puffs",
    name: "Paneer Patties",
    icon: "🥐",
    rating: "4.5",
    votes: "80",
    desc: "Flaky golden puff pastry stuffed with savory spiced cottage cheese filling.",
    tags: ["Snack"],
    isVeg: true,
    hasSizes: false,
    price: 30
  },
  {
    id: "puff-paneer-cheese",
    categoryId: "puffs",
    name: "Paneer Patties (with Cheese)",
    icon: "🧀",
    rating: "4.8",
    votes: "110",
    desc: "Hot layered puff loaded with seasoned paneer and gooey melted cheese.",
    tags: ["Cheesy", "Popular"],
    isVeg: true,
    hasSizes: false,
    price: 40
  },
  {
    id: "puff-mushroom",
    categoryId: "puffs",
    name: "Mushroom Patties",
    icon: "🍄",
    rating: "4.4",
    votes: "45",
    desc: "Crispy puff pastry with sautéed spicy mushroom filling.",
    tags: ["Crispy"],
    isVeg: true,
    hasSizes: false,
    price: 30
  },
  {
    id: "puff-paneer-tikka",
    categoryId: "puffs",
    name: "Paneer Tikka Patties",
    icon: "🍢",
    rating: "4.6",
    votes: "68",
    desc: "Tandoori paneer tikka masala stuffed inside a warm layered puff.",
    tags: ["Spicy"],
    isVeg: true,
    hasSizes: false,
    price: 35
  },
  {
    id: "puff-chilli-cheese-toast",
    categoryId: "puffs",
    name: "Chilli Cheese Toast (2pc)",
    icon: "🍞",
    rating: "4.7",
    votes: "74",
    desc: "2 pieces of toasted garlic bread with spiced green chillies and molten golden cheese.",
    tags: ["2 Pieces"],
    isVeg: true,
    hasSizes: false,
    price: 70
  },
  {
    id: "puff-corn-cheese-ball",
    categoryId: "puffs",
    name: "Corn Cheese Ball (6pc)",
    icon: "🧆",
    rating: "4.8",
    votes: "96",
    desc: "6 crispy fried golden balls filled with sweet corn and melted cheese, served with dip.",
    tags: ["6 Pieces", "Party Snack"],
    isVeg: true,
    hasSizes: false,
    price: 100
  },

  // --- FRIES ---
  {
    id: "fry-french",
    categoryId: "fries",
    name: "French Fries",
    icon: "🍟",
    rating: "4.5",
    votes: "88",
    desc: "Golden crispy potato fries fried fresh and hot, served with ketchup.",
    tags: ["Classic"],
    isVeg: true,
    hasSizes: false,
    price: 100
  },
  {
    id: "fry-salted",
    categoryId: "fries",
    name: "Salted French Fries",
    icon: "🧂",
    rating: "4.5",
    votes: "65",
    desc: "Seasoned with fine sea salt for the authentic crunch taste.",
    tags: ["Crispy"],
    isVeg: true,
    hasSizes: false,
    price: 110
  },
  {
    id: "fry-peri-peri",
    categoryId: "fries",
    name: "Peri Peri French Fries",
    icon: "🌶️",
    rating: "4.9",
    votes: "140",
    desc: "Tossed in fiery and tangy African Peri-Peri spice mix.",
    tags: ["Bestseller", "Spicy"],
    isVeg: true,
    hasSizes: false,
    price: 120
  },
  {
    id: "fry-overloaded",
    categoryId: "fries",
    name: "Over Loaded Cheese Fries",
    icon: "🧀",
    rating: "4.9",
    votes: "152",
    desc: "Crispy fries smothered with liquid cheddar cheese, jalapenos and house sauce.",
    tags: ["Cheesy", "Must Try"],
    isVeg: true,
    hasSizes: false,
    price: 150
  },

  // --- SHAKES ---
  {
    id: "shk-cold-coffee",
    categoryId: "shakes",
    name: "Cold Coffee",
    icon: "☕",
    rating: "4.7",
    votes: "118",
    desc: "Chilled thick blended espresso coffee with creamy rich milk and froth.",
    tags: ["Refreshing"],
    isVeg: true,
    hasSizes: false,
    price: 70
  },
  {
    id: "shk-milk-shake",
    categoryId: "shakes",
    name: "Vanilla Milk Shake",
    icon: "🥛",
    rating: "4.5",
    votes: "55",
    desc: "Classic creamy vanilla sweet milk shake.",
    tags: ["Classic"],
    isVeg: true,
    hasSizes: false,
    price: 70
  },
  {
    id: "shk-chocolate",
    categoryId: "shakes",
    name: "Chocolate Shake",
    icon: "🍫",
    rating: "4.8",
    votes: "105",
    desc: "Rich dark cocoa and chocolate syrup blended with whole milk.",
    tags: ["Choco"],
    isVeg: true,
    hasSizes: false,
    price: 70
  },
  {
    id: "shk-strawberry",
    categoryId: "shakes",
    name: "Strawberry Shake",
    icon: "🍓",
    rating: "4.6",
    votes: "68",
    desc: "Refreshing strawberry fruit shake with rich berry aroma.",
    tags: ["Fruity"],
    isVeg: true,
    hasSizes: false,
    price: 75
  },
  {
    id: "shk-butterscotch",
    categoryId: "shakes",
    name: "Butterscotch Shake",
    icon: "🧈",
    rating: "4.6",
    votes: "72",
    desc: "Creamy butterscotch flavored shake with crunchy caramel pralines.",
    tags: ["Caramel"],
    isVeg: true,
    hasSizes: false,
    price: 75
  },
  {
    id: "shk-pineapple",
    categoryId: "shakes",
    name: "Pineapple Shake",
    icon: "🍍",
    rating: "4.5",
    votes: "49",
    desc: "Tropical sweet pineapple shake served chilled.",
    tags: ["Tropical"],
    isVeg: true,
    hasSizes: false,
    price: 75
  },
  {
    id: "shk-oreo",
    categoryId: "shakes",
    name: "Oreo Shake",
    icon: "🍪",
    rating: "4.9",
    votes: "162",
    desc: "Crunchy Oreo cookies blended with chocolate ice cream & chilled milk.",
    tags: ["Bestseller"],
    isVeg: true,
    hasSizes: false,
    price: 80
  },
  {
    id: "shk-kitkat",
    categoryId: "shakes",
    name: "Kitkat Shake",
    icon: "🍫",
    rating: "4.8",
    votes: "124",
    desc: "Crunchy wafer Kitkat bars blended thick with rich chocolate drizzle.",
    tags: ["Popular"],
    isVeg: true,
    hasSizes: false,
    price: 90
  },
  {
    id: "shk-badam-thandai",
    categoryId: "shakes",
    name: "Badam Thandai Shake",
    icon: "🥛",
    rating: "4.8",
    votes: "86",
    desc: "Traditional rich almond, pistachio and saffron-cardamom thandai shake.",
    tags: ["Desi Special"],
    isVeg: true,
    hasSizes: false,
    price: 90
  },
  {
    id: "shk-brownie",
    categoryId: "shakes",
    name: "Brownie Shake",
    icon: "🥧",
    rating: "4.9",
    votes: "140",
    desc: "Decadent fudge brownie chunks blended into a thick velvety milkshake.",
    tags: ["Bestseller", "Rich"],
    isVeg: true,
    hasSizes: false,
    price: 130
  },
  {
    id: "shk-ferrero",
    categoryId: "shakes",
    name: "Ferrero Rocher Shake",
    icon: "🍫",
    rating: "4.9",
    votes: "158",
    desc: "Premium hazelnut Ferrero Rocher chocolates blended with Nutella chocolate shake.",
    tags: ["Premium"],
    isVeg: true,
    hasSizes: false,
    price: 150
  },

  // --- MOJITOS ---
  {
    id: "moj-green-granny",
    categoryId: "mojitos",
    name: "Green Granny Mojito",
    icon: "🍏",
    rating: "4.6",
    votes: "58",
    desc: "Crisp green apple flavors infused with mint, lime and sparkling fizz.",
    tags: ["Apple Mint"],
    isVeg: true,
    hasSizes: false,
    price: 70
  },
  {
    id: "moj-watermelon",
    categoryId: "mojitos",
    name: "Watermelon Mojito",
    icon: "🍉",
    rating: "4.7",
    votes: "64",
    desc: "Refreshing sweet watermelon crush with fresh mint leaves and soda.",
    tags: ["Summer"],
    isVeg: true,
    hasSizes: false,
    price: 70
  },
  {
    id: "moj-orange-malt",
    categoryId: "mojitos",
    name: "Orange Malt Mojito",
    icon: "🍊",
    rating: "4.5",
    votes: "46",
    desc: "Citrusy orange punch combined with sparkling ice and lemon mint.",
    tags: ["Citrus"],
    isVeg: true,
    hasSizes: false,
    price: 70
  },
  {
    id: "moj-blue-curacao",
    categoryId: "mojitos",
    name: "Blue Curacao Mojito",
    icon: "🔵",
    rating: "4.8",
    votes: "88",
    desc: "Vibrant electric blue curacao beverage with lemon zest and soda.",
    tags: ["Popular"],
    isVeg: true,
    hasSizes: false,
    price: 70
  },
  {
    id: "moj-kala-khatta",
    categoryId: "mojitos",
    name: "Kala Khatta Mojito",
    icon: "🍇",
    rating: "4.7",
    votes: "79",
    desc: "Desi tangy sweet blackberry flavor with black salt and lime burst.",
    tags: ["Desi Tangy"],
    isVeg: true,
    hasSizes: false,
    price: 70
  },
  {
    id: "moj-spicy-lemon",
    categoryId: "mojitos",
    name: "Spicy Lemon Mojito",
    icon: "🍋",
    rating: "4.5",
    votes: "52",
    desc: "Zesty lemon and crushed ice with a mild spicy pepper kick.",
    tags: ["Zesty"],
    isVeg: true,
    hasSizes: false,
    price: 70
  },
  {
    id: "moj-mint",
    categoryId: "mojitos",
    name: "Virgin Mint Mojito",
    icon: "🌿",
    rating: "4.8",
    votes: "95",
    desc: "Classic Cuban virgin mojito with crushed fresh garden mint and lime.",
    tags: ["Classic"],
    isVeg: true,
    hasSizes: false,
    price: 70
  },

  // --- DESSERTS & CAKES ---
  {
    id: "dst-chocolate-donut",
    categoryId: "desserts",
    name: "Chocolate Donuts",
    icon: "🍩",
    rating: "4.5",
    votes: "62",
    desc: "Soft glazed donut ring coated with rich chocolate glaze.",
    tags: ["Sweet"],
    isVeg: true,
    hasSizes: false,
    price: 40
  },
  {
    id: "dst-lava-cake",
    categoryId: "desserts",
    name: "Choco Lava Cake",
    icon: "🌋",
    rating: "4.9",
    votes: "185",
    desc: "Warm chocolate cake with molten oozing chocolate fudge center.",
    tags: ["Bestseller", "Must Try"],
    isVeg: true,
    hasSizes: false,
    price: 40
  },
  {
    id: "dst-black-forest",
    categoryId: "desserts",
    name: "Black Forest Pastry",
    icon: "🍰",
    rating: "4.7",
    votes: "75",
    desc: "Layered chocolate sponge cake with fresh whipped cream and cherry topping.",
    tags: ["Classic"],
    isVeg: true,
    hasSizes: false,
    price: 50
  },
  {
    id: "dst-pineapple-pastry",
    categoryId: "desserts",
    name: "Pineapple Pastry",
    icon: "🍍",
    rating: "4.6",
    votes: "60",
    desc: "Light vanilla sponge infused with juicy tropical pineapple compote.",
    tags: ["Fruity"],
    isVeg: true,
    hasSizes: false,
    price: 50
  },
  {
    id: "dst-chocolate-pastry",
    categoryId: "desserts",
    name: "Chocolate Truffle Pastry",
    icon: "🍫",
    rating: "4.8",
    votes: "92",
    desc: "Truffle chocolate sponge layered with rich dark ganache.",
    tags: ["Choco"],
    isVeg: true,
    hasSizes: false,
    price: 50
  },
  {
    id: "dst-rasmalai-pastry",
    categoryId: "desserts",
    name: "Rasmalai Pastry",
    icon: "🟡",
    rating: "4.9",
    votes: "118",
    desc: "Fusion dessert of soft cardamom sponge soaked in aromatic saffron rasmalai milk.",
    tags: ["Indian Fusion", "Popular"],
    isVeg: true,
    hasSizes: false,
    price: 60
  },
  {
    id: "dst-red-velvet",
    categoryId: "desserts",
    name: "Red Velvet Pastry",
    icon: "🍰",
    rating: "4.8",
    votes: "84",
    desc: "Velvety crimson sponge layered with silky smooth cream cheese frosting.",
    tags: ["Red Velvet"],
    isVeg: true,
    hasSizes: false,
    price: 70
  },
  {
    id: "dst-hot-brownie",
    categoryId: "desserts",
    name: "Hot Chocolate Brownie",
    icon: "🥧",
    rating: "4.8",
    votes: "105",
    desc: "Dense dark chocolate walnut brownie served warm with chocolate drizzle.",
    tags: ["Warm Brownie"],
    isVeg: true,
    hasSizes: false,
    price: 80
  },
  {
    id: "dst-brownie-icecream",
    categoryId: "desserts",
    name: "Brownie with Ice Cream",
    icon: "🍨",
    rating: "4.9",
    votes: "142",
    desc: "Warm chocolate fudge brownie served with a scoop of vanilla ice cream & hot chocolate.",
    tags: ["Bestseller"],
    isVeg: true,
    hasSizes: false,
    price: 120
  },
  {
    id: "dst-blueberry-cheesecake",
    categoryId: "desserts",
    name: "Blueberry Cheesecake (100g)",
    icon: "🫐",
    rating: "4.9",
    votes: "110",
    desc: "Creamy New York style cheesecake topped with luscious wild blueberry glaze.",
    tags: ["Cheesecake", "Popular"],
    isVeg: true,
    hasSizes: false,
    price: 70
  },
  {
    id: "dst-oreo-cheesecake",
    categoryId: "desserts",
    name: "Oreo Cheesecake",
    icon: "🍪",
    rating: "4.8",
    votes: "95",
    desc: "Cookies and cream cheesecake with crunchy Oreo crust and cream topping.",
    tags: ["Cheesecake"],
    isVeg: true,
    hasSizes: false,
    price: 70
  },
  {
    id: "dst-hazelnut-cheesecake",
    categoryId: "desserts",
    name: "Hazelnut Cheesecake",
    icon: "🌰",
    rating: "4.8",
    votes: "88",
    desc: "Nutty roasted hazelnut cream infused in smooth baked cheesecake.",
    tags: ["Cheesecake"],
    isVeg: true,
    hasSizes: false,
    price: 70
  },
  {
    id: "dst-mousse-cake",
    categoryId: "desserts",
    name: "Triple Layer Mousse Cake",
    icon: "🍫",
    rating: "4.8",
    votes: "79",
    desc: "Three layers of dark, milk and white chocolate mousse on light sponge.",
    tags: ["Triple Mousse"],
    isVeg: true,
    hasSizes: false,
    price: 70
  },
  {
    id: "dst-honey-cheesecake",
    categoryId: "desserts",
    name: "Bee Honey Cheesecake",
    icon: "🍯",
    rating: "4.7",
    votes: "72",
    desc: "Natural wild bee honey glazed baked cheesecake with sweet delicate aroma.",
    tags: ["Cheesecake"],
    isVeg: true,
    hasSizes: false,
    price: 70
  }
];

const APP_CONFIG = {
  storeName: "Mr Pizzeria",
  parentBrand: "Shivhari Food Delivery",
  location: "Bikramganj, Bihar",
  minOrderAmount: 99,
  deliveryTimeEstimate: "20-25 mins",
  deliveryFee: 0, // Free or standard note
  whatsappCatalogUrl: "https://wa.me/p/26847706081597311/128256430854321",
  currencySymbol: "₹"
};
